blank_issues_enabled: true

contact_links:
  - name: Report a security vulnerability
    url: https://github.com/rtCamp/carousel-kit/security/policy
    about: Please review our security policy for details
