name: Enhancement
description: Suggest an idea for this project.
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Describe the feature or improvement you'd like.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: Explain the problem this feature would solve.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Describe any alternative solutions or approaches you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any context, examples, or screenshots.
    validations:
      required: false
